Repository Utfprpb-oficina-20251/server, pull requests merged in 2025-06, with the labels that each got.

#74 chore - java format
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthController.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthService.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/dto/SolicitacaoCodigoOTPRequestDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/dto/SolicitacaoCodigoOTPResponseDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/jwt/JwtService.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/otp/EmailOtpAuthenticationProvider.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/otp/EmailOtpAuthenticationToken.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/OpenApiConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/WebConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCode.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeDto.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeValidationService.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailController.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/error/ErrorHandler.java
  src/main/java/br/edu/utfpr/pb/ext/server/generics/CrudController.java
  src/main/java/br/edu/utfpr/pb/ext/server/generics/CrudServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/generics/ICrudService.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/SugestaoDeProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/SugestaoDeProjetoRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/service/SugestaoDeProjetoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/IUsuarioService.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/authority/AuthorityRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/dto/UsuarioAlunoRequestDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/dto/UsuarioProjetoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/dto/UsuarioServidorRequestDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/validation/UniqueRaValidador.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/validation/UniqueSiapeValidator.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthServiceTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthTestConfig.java
Labels: documentation

#85 Bugfix/ajuste objeto solicitacao otp
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthController.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthService.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/dto/RespostaLoginDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/dto/UsuarioLoginDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/Usuario.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioServiceImplTest.java
Labels: enhancement

#75 Pext 76 86 departamento responsavel retornar por endpoint
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/Departamento.java
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoDto.java
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoServiceImpl.java
  src/main/resources/db/migration/V1.2.4__create_tb_departamento.sql
  src/test/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoServiceTest.java
Labels: documentation, enhancement

#79 Feature/pext 91
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/error/ExceptionHandlerAdvice.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/IProjetoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/security/SecurityService.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImplTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/security/SecurityServiceTest.java
Labels: documentation, enhancement

#73 feature/PEXT-117-Template-OTP
  pom.xml
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthController.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthService.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/error/ExceptionHandlerAdvice.java
  src/main/java/br/edu/utfpr/pb/ext/server/generics/CrudServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/IProjetoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/security/SecurityService.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/main/resources/application.yml
  src/main/resources/templates/otp-template.html
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoServiceTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/email/EmailControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImplTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImplTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/security/SecurityServiceTest.java
Labels: documentation, enhancement

#90 feature/PEXT-119-Enum-Email
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthService.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/otp/EmailOtpAuthenticationProvider.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCode.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeDto.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeValidationService.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailController.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/enums/TipoCodigo.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImpl.java
  src/main/resources/templates/otp-template.html
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/email/EmailControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImplTest.java
Labels: documentation, enhancement

#94 PEXT-125 feat: Add UsuarioLogadoInfoDTO and implement getMeuPerfil endpoint
  src/main/java/br/edu/utfpr/pb/ext/server/auth/AuthService.java
  src/main/java/br/edu/utfpr/pb/ext/server/auth/otp/EmailOtpAuthenticationProvider.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCode.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailCodeValidationService.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/EmailController.java
  src/main/java/br/edu/utfpr/pb/ext/server/email/impl/EmailServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/dto/UsuarioLogadoInfoDTO.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioControllerTest.java
Labels: documentation, enhancement

#96 PEXT-33 feat: Add endpoint to retrieve all users and update security configuration
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/test/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioControllerTest.java
Labels: documentation, enhancement

#99 bugfix/permissao-acesso-departamentos-incorreta
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/curso/Curso.java
  src/main/java/br/edu/utfpr/pb/ext/server/curso/CursoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/curso/CursoRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/curso/CursoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/curso/CursoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/generics/CrudServiceImpl.java
Labels: documentation, enhancement

#105 retorno mensagem email errado equipe executora
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
Labels: documentation, enhancement

#107 PEXT-151 feat: add cargaHoraria and qtdeVagas fields to Projeto and ProjetoDTO, and update related services
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/Projeto.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoDTO.java
  src/main/resources/db/migration/V1.3.2__add_qtdeVagas_e_cargaHoraria.sql
Labels: documentation, enhancement

#77 Pext 99 criar endpoint para cancelamento de projeto
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/CancelamentoProjetoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/IProjetoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/Projeto.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
  src/main/resources/db/migration/V.1.2.5__alter_tb_projeto.sql
  src/test/java/br/edu/utfpr/pb/ext/server/departamento/DepartamentoServiceTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImplTest.java
Labels: documentation, enhancement

#110 add migration faltando cancelamento projto
  src/main/resources/db/migration/V1.3.3__add_motivo_cancelamento_projeto.sql
Labels: documentation

#112 PEXT156 bugfix:add quantity and workload fields to project creation
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/dto/UsuarioServidorRequestDTO.java
Labels: documentation, enhancement

#113 PEXT-160 feat: add endpoint to list project suggestions for logged-in user
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/SugestaoDeProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/service/SugestaoDeProjetoServiceImpl.java
  src/test/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/SugestaoDeProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/service/SugestaoDeProjetoServiceImplTest.java
Labels: documentation, enhancement

#103 Feature/pext 126+111
  src/main/java/br/edu/utfpr/pb/ext/server/config/SecurityConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/FiltroProjetoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/IProjetoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerIntegrationTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImplTest.java
Labels: documentation, enhancement

#114 Feature/integracao minio
  README.md
  docker-compose.yml
  pom.xml
  src/main/java/br/edu/utfpr/pb/ext/server/config/MinioConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/MinioInitializer.java
  src/main/java/br/edu/utfpr/pb/ext/server/file/FileController.java
  src/main/java/br/edu/utfpr/pb/ext/server/file/FileInfoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/file/FileService.java
  src/main/java/br/edu/utfpr/pb/ext/server/file/exception/FileException.java
  src/main/resources/application.yml
  src/test/java/br/edu/utfpr/pb/ext/server/ServerApplicationTests.java
  src/test/java/br/edu/utfpr/pb/ext/server/auth/AuthControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/config/AuthTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/config/MinioTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/file/FileControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/file/FileServiceTest.java
Labels: documentation, enhancement

#119 adicionando validação de id diferente de null antes de definir status…
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/service/SugestaoDeProjetoServiceImpl.java
Labels: enhancement

#120 fix - solução temporária para tratamento de imagem no endpoint de atualização de projeto já que o mesmo não usa o CRUDService
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
Labels: enhancement

#121 feature/PEXT-186-adicionar-responsavel-dto
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoDTO.java
Labels: documentation, enhancement

#122 PEXT-189 feat: add endpoint to search users by email
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioController.java
  src/test/java/br/edu/utfpr/pb/ext/server/usuario/UsuarioControllerTest.java
Labels: documentation, enhancement

#127 incremento de filtros de projeto
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/FiltroProjetoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/sugestaoprojeto/service/SugestaoDeProjetoServiceImpl.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerIntegrationTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/projeto/ProjetoServiceImplTest.java
Labels: documentation, enhancement

#126 feat: implementa candidatura com endpoint, service, testes e migration
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/Candidatura.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaController.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/ICandidaturaService.java
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/StatusCandidatura.java
  src/main/resources/db/migration/V1.3.6__create_table_tb_candidatura.sql
  src/test/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaServiceImplTest.java
Labels: documentation, enhancement

#129 feature/tabela-notificacao
  src/main/java/br/edu/utfpr/pb/ext/server/config/OpenApiConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/config/WebConfig.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/Notificacao.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoRepository.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/dto/NotificacaoDTO.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/enums/TipoNotificacao.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/enums/TipoReferencia.java
  src/main/java/br/edu/utfpr/pb/ext/server/usuario/Usuario.java
  src/main/resources/db/migration/V1.3.7__create_table_notificacao.sql
  src/test/java/br/edu/utfpr/pb/ext/server/config/JwtTestConfig.java
  src/test/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoControllerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoServiceImplTest.java
Labels: documentation, enhancement

#131 fix - renomeado o dto para bater com o nome correto da entidade
  src/main/java/br/edu/utfpr/pb/ext/server/candidatura/CandidaturaDTO.java
Labels: documentation, enhancement

#132 feature/gerar-notificacao
  src/main/java/br/edu/utfpr/pb/ext/server/event/NotificacaoEventListener.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoController.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoService.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoServiceImpl.java
  src/main/java/br/edu/utfpr/pb/ext/server/notificacao/enums/TipoReferencia.java
  src/test/java/br/edu/utfpr/pb/ext/server/event/CandidaturaEventTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/event/NotificacaoEventListenerTest.java
  src/test/java/br/edu/utfpr/pb/ext/server/notificacao/NotificacaoServiceImplTest.java
Labels: documentation, enhancement
